// <auto-generated />
using System;
using HR_Platform_Intens.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HR_Platform_Intens.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HR_Platform_Intens.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ContractNumber")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1995, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractNumber = 1,
                            Email = "marko@mail.com",
                            FullName = "Marko Petrovic"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1997, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractNumber = 2,
                            Email = "pera@mail.com",
                            FullName = "Petar Nikolic"
                        });
                });

            modelBuilder.Entity("HR_Platform_Intens.Models.CandidateSkill", b =>
                {
                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("CandidateId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkills");

                    b.HasData(
                        new
                        {
                            CandidateId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 2
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 4
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 5
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 6
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 8
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 10
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 12
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 13
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 17
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 19
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 21
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 2
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 3
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 4
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 5
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 6
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 9
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 10
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 12
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 13
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 20
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 19
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 21
                        });
                });

            modelBuilder.Entity("HR_Platform_Intens.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 2,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Javascript"
                        },
                        new
                        {
                            Id = 5,
                            Name = "HTML"
                        },
                        new
                        {
                            Id = 6,
                            Name = "CSS"
                        },
                        new
                        {
                            Id = 7,
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 8,
                            Name = "React"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Azure"
                        },
                        new
                        {
                            Id = 11,
                            Name = "AWS"
                        },
                        new
                        {
                            Id = 12,
                            Name = "OOP"
                        },
                        new
                        {
                            Id = 13,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Git"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Django"
                        },
                        new
                        {
                            Id = 16,
                            Name = "MongoDb"
                        },
                        new
                        {
                            Id = 17,
                            Name = "QA"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Xamarin"
                        },
                        new
                        {
                            Id = 19,
                            Name = "JSON"
                        },
                        new
                        {
                            Id = 20,
                            Name = "XML"
                        },
                        new
                        {
                            Id = 21,
                            Name = "English"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Russian"
                        },
                        new
                        {
                            Id = 23,
                            Name = "German"
                        },
                        new
                        {
                            Id = 24,
                            Name = "French"
                        });
                });

            modelBuilder.Entity("HR_Platform_Intens.Models.CandidateSkill", b =>
                {
                    b.HasOne("HR_Platform_Intens.Models.Candidate", "Candidate")
                        .WithMany("Skills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Platform_Intens.Models.Skill", "Skill")
                        .WithMany("Candidates")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("HR_Platform_Intens.Models.Candidate", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("HR_Platform_Intens.Models.Skill", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
